# Generated by Django 3.1.7 on 2021-03-16 14:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hastane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ILCE_ADI', models.CharField(max_length=200)),
                ('ADI', models.CharField(max_length=200)),
                ('ALT_KATEGORI', models.CharField(max_length=200)),
                ('ADRES', models.CharField(max_length=400)),
                ('TELEFON', models.CharField(max_length=200)),
                ('WEBSITESI', models.CharField(max_length=200)),
                ('ACIL_SERVIS', models.CharField(max_length=200)),
                ('YATAK', models.IntegerField(null=True)),
                ('AMBULANS', models.CharField(max_length=200)),
                ('MAHALLE', models.CharField(max_length=200)),
                ('POINT', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
