# Generated by Django 3.1.7 on 2021-03-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hastane',
            new_name='Saglik',
        ),
    ]
